# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
name: ant design pro

trigger:
  - master

jobs:
  - job: lintAndBuild

    pool:
      vmImage: 'Ubuntu-16.04'

    steps:
      - checkout: self
        clean: outputs
      - task: NodeTool@0
        inputs:
          versionSpec: '11.x'
      - script: yarn install
        displayName: install
      - script: npm run lint
        displayName: lint
      - script: npm run build
        env:
          PROGRESS: none
        displayName: build
      - script: npm run test
        env:
          PROGRESS: none
        displayName: test
